pipeline {
    agent any {
        stages {
            stage ('git checkout') {
                steps {
                    checkout([$class: 'GitSCM', branches: [[name: '*/master']], extensions: [], userRemoteConfigs: [[url: 'https://github.com/mani-2022/simple-maven-project.git']]])
                }
            }
        }
    }
}
