pipeline {
    agent any {
        stages {
            stage ('git checkout') {
                steps {
                    git 'https://github.com/mani-2022/simple-maven-project.git'
                }
            }
        }
    }
}
